# ============================================================
# Active Profile
# ============================================================
spring.profiles.active=local

# ============================================================
# Application
# ============================================================
spring.application.name=work-action-service